from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns


def plot_confusion_matrix(y_true, y_pred, title):
    '''
    To plot a heatmap representation of the confusion matrix, which shows the counts of 
    true positive, true negative, false positive, and false negative predictions made by a classification model.
    Parameters:
        y_true: the true labels or target values of the dataset.
        y_pred: the predicted labels generated by the classification model.
        title: the title of the plot, typically describing the context of the confusion matrix. 
    '''

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.title(title)
    plt.show()